global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'starpets'
    scrape_interval: 5s
    dns_sd_configs:
      - names: ['app']
        type: 'A'
        port: 3000
    metrics_path: '/metrics'
